steps:
  # Build Docker image for the frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/project897927/frontend:$SHORT_SHA', './frontend']

  # Build Docker image for the backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/project897927/backend:$SHORT_SHA', './backend']

  # Push the frontend image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/project897927/frontend:$SHORT_SHA']

  # Push the backend image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/project897927/backend:$SHORT_SHA']

  # Set up the GKE cluster (Autopilot mode)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'create-auto'
      - 'your-autopilot-cluster'
      - '--region'
      - 'your-region'
    waitFor:
      - '-'

  # Deploy the frontend application to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'frontend/deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=your-region'
      - 'CLOUDSDK_CONTAINER_CLUSTER=your-autopilot-cluster'

  # Deploy the backend application to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'backend/deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=your-region'
      - 'CLOUDSDK_CONTAINER_CLUSTER=your-autopilot-cluster'

  # Expose the frontend deployment with a service
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'frontend/service.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=your-region'
      - 'CLOUDSDK_CONTAINER_CLUSTER=your-autopilot-cluster'

  # Expose the backend deployment with a service
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'backend/service.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=your-region'
      - 'CLOUDSDK_CONTAINER_CLUSTER=your-autopilot-cluster'

images:
  - 'gcr.io/project897927/frontend:$SHORT_SHA'
  - 'gcr.io/project897927/backend:$SHORT_SHA'
