logsBucket: gs://bucket897927

substitutions:
  _REGION: 'us-central1'  # Default region, can be overridden in the trigger
  _CLUSTER_NAME: 'navicluster'  # Default cluster name, can be overridden in the trigger

steps:
  # Step 1: Build Docker image for the frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/project897927/frontend:latest', './frontend']
    id: 'build-frontend'

  # Step 2: Build Docker image for the backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/project897927/backend:latest', './backend']
    id: 'build-backend'
    waitFor:
      - 'build-frontend'

  # Step 3: Push the frontend image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/project897927/frontend:latest']
    id: 'push-frontend'
    waitFor:
      - 'build-backend'

  # Step 4: Push the backend image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/project897927/backend:latest']
    id: 'push-backend'
    waitFor:
      - 'push-frontend'

  # Step 5: Check if the GKE cluster exists
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if gcloud container clusters describe "${_CLUSTER_NAME}" --region "${_REGION}" > /dev/null 2>&1; then
          echo "Cluster already exists."
          echo "CLUSTER_EXISTS=true" > /workspace/cluster_exists.txt
        else
          echo "Cluster does not exist."
          echo "CLUSTER_EXISTS=false" > /workspace/cluster_exists.txt
        fi
    id: 'check-cluster'
    waitFor:
      - 'push-backend'

  # Step 6: Get an access token
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ACCESS_TOKEN=$(gcloud auth print-access-token)
        echo $ACCESS_TOKEN > /workspace/access_token.txt
    id: 'fetch-access-token'
    waitFor:
      - 'check-cluster'

  # Step 7: Apply Terraform configuration if the cluster does not exist
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if grep -q CLUSTER_EXISTS=true /workspace/cluster_exists.txt; then
          echo "Skipping Terraform apply as cluster exists."
        else
          echo "Cluster does not exist. Running Terraform apply."
          export GOOGLE_OAUTH_ACCESS_TOKEN=$(cat /workspace/access_token.txt)
          cd terraform
          terraform init
          terraform apply -auto-approve
        fi
    id: 'terraform-apply'
    waitFor:
      - 'fetch-access-token'

  # Step 8: Extract cluster credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials "${_CLUSTER_NAME}" --region "${_REGION}"
    id: 'get-credentials'
    waitFor:
      - 'terraform-apply'

  # Step 9: Deploy the frontend application to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'frontend/deployment.yaml']
    id: 'deploy-frontend'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
    waitFor:
      - 'get-credentials'

  # Step 10: Deploy the backend application to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'backend/deployment.yaml']
    id: 'deploy-backend'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
    waitFor:
      - 'deploy-frontend'

  # Step 11: Expose the frontend deployment with a service
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'frontend/service.yaml']
    id: 'expose-frontend-service'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
    waitFor:
      - 'deploy-backend'

  # Step 12: Expose the backend deployment with a service
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'backend/service.yaml']
    id: 'expose-backend-service'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
    waitFor:
      - 'expose-frontend-service'

images:
  - 'gcr.io/project897927/frontend:latest'
  - 'gcr.io/project897927/backend:latest'
